# EJEMPLO PARA USUARIOS EXTERNOS
apiVersion: v1
kind: Secret
metadata:
  name: gemini-api-secret
type: Opaque
stringData:
  # Si clonas el repo debes poner aquí tu propia clave
  GEMINI_API_KEY: "TU_CLAVE_AQUI"