apiVersion: v1
kind: Service
metadata:
  name: rag-bot-service
spec:
  type: NodePort # Permite acceder desde el navegador del ordenador
  selector:
    app: rag-bot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000 # Accederemos a través de localhost:30000